"""Add applications table

Revision ID: d1286330359d
Revises: d2e3f4a5b6c7
Create Date: 2026-03-22 17:34:45.071078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1286330359d'
down_revision: Union[str, Sequence[str], None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('adzuna_id', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('empresa', sa.String(length=300), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'adzuna_id', name='uq_application_user_adzuna')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.drop_constraint(op.f('search_cache_perfil_hash_key'), 'search_cache', type_='unique')
    op.drop_index(op.f('ix_search_cache_perfil_hash'), table_name='search_cache')
    op.create_index(op.f('ix_search_cache_perfil_hash'), 'search_cache', ['perfil_hash'], unique=True)
    op.create_index(op.f('ix_search_cache_id'), 'search_cache', ['id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_search_cache_id'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_perfil_hash'), table_name='search_cache')
    op.create_index(op.f('ix_search_cache_perfil_hash'), 'search_cache', ['perfil_hash'], unique=False)
    op.create_unique_constraint(op.f('search_cache_perfil_hash_key'), 'search_cache', ['perfil_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
